### ISSUE TITLE
raft: provide protection against unbounded Raft log growth

### ISSUE THREAD

**Issue by siddontang** [tikv/raft-rs#131]
Introduce a new, optional `max_uncommitted_entries` configuration. This config limits the max number of uncommitted entries that may be appended to a leader's log. Once this limit is exceeded, proposals will begin to return `ProposalDropped` errors.

You can refer to refer  https://github.com/etcd-io/etcd/pull/10167

This issue can be closed by:

* Modifying the [`Config`](https://github.com/pingcap/raft-rs/blob/master/src/config.rs#L35) to have this new configuration setting.
* Modify [`Raft::handle_append_entries`](https://github.com/pingcap/raft-rs/blob/master/src/raft.rs#L1666-L1674) to check the limit. You can return the existing [`ProposalDropped`](https://github.com/pingcap/raft-rs/blob/master/src/errors.rs#L44) error.
* Adding a test to `tests/integration_cases/test_raft.rs` similar to the one in the etcd PR.

As always, if you'd like to tackle this, or need any help, please feel free to reach out! We'd love to get you involved.

**Comment by Hoverbear** [comment]
@utsl42 mentioned they might want to take a [crack at this](https://twitter.com/utsl42/status/1059816059644137473).

**Comment by Ishiihara** [comment]
@siddontang @Hoverbear I am interested in taking this issue, can you assign this to me?

**Comment by Hoverbear** [comment]
@Ishiihara Please consider yourself assigned! (We can't assign you an issue on github until you have a merge I think...)

Do you think you could start from #139, or are you planning to start from scratch?

**Comment by DanteLee** [comment]
Hi, i made a new PR working on this issue and code is ready for review. Glad to join the community :)
