### ISSUE TITLE
Fast log append rejection

### ISSUE THREAD

**Issue by BusyJay** [tikv/raft-rs#246]
When leader sends append to a follower, follower may reject the messages. However, it only sets its own last index, so there is no way leader can find what's the conflict they have. So leader has to decrease the progress one by one and detect whether it's accepted by the follower. The progress can be very slow and wasteful if there are too many pending logs in the old leader, which is just recovered from a long isolation, because the logs need be sent over and over again.

I suggest to add a hint for the term of last index. If the new leader know the term of the follower's last index, it can jump to the last log in the given term directly and start replicated. So there will be just one round of RPC to figure out the conflict.

For example,

OL: 1222333333333333333
NL: 124444444

The number is the term of the log. In the old implement, new leader has to decrease the progress one by one to walk through all the '4's. But if it can know that the term of OL's last index, it can jump to 2 directly, and starts replicate logs from 2.

**Comment by accelsao** [comment]
They merge the code, https://github.com/etcd-io/etcd/pull/11964
I can redo this issue
