### ISSUE TITLE
Maybe replace 'nodes' with 'voters' in ConfState

### ISSUE THREAD

**Issue by Fullstop000** [tikv/raft-rs#277]
In `ConfState`, we have `nodes` with `learners` which might be a little unclear since the `nodes` is representing the voters.

There is also a help method `get_voters` in `ConfState` but it seems not being used in the current implementation
https://github.com/pingcap/raft-rs/blob/0632bcfc1ce4cd60812959758b7c8645f8d42458/proto/src/lib.rs#L24-L28

@Hoverbear

**Comment by hicqu** [comment]
It's done!

**Comment by Hoverbear** [comment]
Amazing. Good job!

![Good job!](https://media.giphy.com/media/d31uStsh7jvzzzVK/200w_d.gif)
