### ISSUE TITLE
Use async/await and futures 0.3

### ISSUE THREAD

**Issue by nrc** [tikv/raft-rs#297]
Async/await is on the path to stable, and is much clearer to read and write than raw futures. Tokio is also working on futures 0.3 native support, so it would be great to use async/await and futures 0.3 in Raft.

**Comment by psinghal20** [comment]
Hey @nrc! I would love to work on it. I haven't had any first-hand experience with Async/Await in rust but have been reading about it a little. Could you give me some pointers where to begin?

**Comment by nrc** [comment]
@psinghal20 A good place to start would be to look at the TiKV Rust client - if you look through the commits, you should find a few which move from 0.1 futures to 0.3 futures and from 0.3 futures to async/await (the latter step is usually fairly straightforward). You can read about the 0.1 to 0.3 migration in this blog post: https://tikv.org/blog/client-futures/ For Raft, you should go straight from 0.1 futures to async/await. The interesting bit is that you will need to use the compatability layer because upstream crates are still using 0.1 futures.

You can convert one future at a time, you don't need to do everything at once.

Once you've had a look at those links, let me know if you have more questions!

**Comment by nrc** [comment]
@psinghal20 it might be easier by starting with the migration in grpc-rs (https://github.com/pingcap/grpc-rs/issues/237) since that is upstream of Raft.

**Comment by hicqu** [comment]
Seems in raft-rs futures is not used directly. :)

**Comment by Kerollmops** [comment]
Is this issue still relevant?

**Comment by BusyJay** [comment]
As @hicqu suggested, raft-rs doesn't use futures at all, so there is no work need to do in raft-rs.
