### ISSUE TITLE
Maybe inaccurate comments for `has_next_entries_since`

### ISSUE THREAD

**Issue by Fullstop000** [tikv/raft-rs#304]
The comment of `has_next_entries_since` is a little confused:
https://github.com/pingcap/raft-rs/blob/387631247f840f56c8f40575ddf5963e6a384c58/src/raft_log.rs#L388-L392
It actually checks whether there are some entries that can be applied between `since_idx` and `committed_idx`.

**Comment by Fullstop000** [comment]
Here is the story where I found this:
I tried to use this as a part of grouping followers who need snapshots in Follower Replication implementation. After test cases went red, I realized I was "fooled" by the comment🤦‍♂️.

**Comment by Hoverbear** [comment]
Thanks for reporting this @Fullstop000 :) Sorry for the confusion.
