### ISSUE TITLE
Maybe we can remove `hashbrown`

### ISSUE THREAD

**Issue by koushiro** [tikv/raft-rs#306]
The `hashbrown` is the HashMap implementation for the standard library since rustc 1.36.
If we remove the `hashbrown` dependency, then we need to bump the minimum supported rustc version to 1.36.

**Comment by nrc** [comment]
Yes! We should definitely do this. (If anyone objects to increasing the minimum supported version, then we can make it a Cargo feature, but I personally think we should just do it).
