### ISSUE TITLE
The Raft Paper is not available.

### ISSUE THREAD

**Issue by YasinEnigma** [tikv/raft-rs#323]
the Raft Paper link in the Links for Further Research part is not available. the file is not found.

**Comment by Fullstop000** [comment]
@YasinEnigma You can refer to https://raft.github.io/raft.pdf :)

**Comment by YasinEnigma** [comment]
> @YasinEnigma You can refer to https://raft.github.io/raft.pdf :)
oh thanks :)

**Comment by nrc** [comment]
Lets leave this open until the link is fixed

**Comment by stoksc** [comment]
opened https://github.com/tikv/raft-rs/pull/342, not sure how to link
