### ISSUE TITLE
Add a way to figure out followers commit index

### ISSUE THREAD

**Issue by BusyJay** [tikv/raft-rs#325]
Raft doesn't requires follower reports its commit index. But aggregated them can help us find out whether a log is committed in all nodes, which is quite useful in some cases.

For example, in TiKV, when enabling hibernate regions, it's better to let all the followers to commit to latest logs before going to sleep, otherwise follower can wait for a long time before committing and applying logs, which can hurt follower reads.

It can also be used in merge too.

**Comment by Fullstop000** [comment]
It looks like that the leader can have all the committed indexes and send a message to catch up followers with an out-of-date commit index. 
Is there any other use cases besides the hibernate regions? In common situations, the commit index will be synced through `MsgHeartbeat`.

**Comment by BusyJay** [comment]
All situations that relies on consistency overall replicas instead of quorum can utilize the information. It's not going to change the log replication algo, it just records follower's commit index besides its last index in the progress. The goal here is to expose additional information.

**Comment by Fullstop000** [comment]
Is this landed in TiKV? Otherwise, I'd like to have a try :)

**Comment by BusyJay** [comment]
No, it has not been implemented yet. Feel free to try!

**Comment by accelsao** [comment]
would you like the vector of committed index? and where to record it? in `Ready` structure?

**Comment by BusyJay** [comment]
It should be stored in the Progress, just like `matched` and other fields.
