### ISSUE TITLE
Allow customize quorum

### ISSUE THREAD

**Issue by BusyJay** [tikv/raft-rs#331]
I suggest add an customize quorum function hook. The hook can produce any number between [n / 2 + 1, n], where n is the number of available voters. So that we can make data safer in some cases.

/cc @siddontang @disksing @hicqu

**Comment by Hoverbear** [comment]
@BusyJay Do you think we could flesh this out a bit?

**Comment by BusyJay** [comment]
For example, deploy odd number of replicas in two data center can not guarantee data safe if a data center is completely destroyed. Deploy even number of replicas without joint consensus is not safe either, as conf change is done step by step, so that the cluster replicas have to become odd at some time.

**Comment by Hoverbear** [comment]
Okay! So this would mean supporting dynamic quorum configuration? We could add a log entry that's a qourum change?

**Comment by BusyJay** [comment]
A log entry will not take effect in time. Exposing the hook is the most flexible way.

**Comment by Fullstop000** [comment]
Does this feature affect the incoming joint consensus?

**Comment by BusyJay** [comment]
No, it just provides a safer quorum number.

**Comment by BusyJay** [comment]
Implemented by #336.
