### ISSUE TITLE
Upgrading Prost

### ISSUE THREAD

**Issue by hntd187** [tikv/raft-rs#335]
Hi, are there any plans to upgrade prost to it's 0.6.1 version? It includes a security fix as in addition to lots of other updates. https://github.com/danburkert/prost/releases/tag/v0.6.1 

I know there are many upstream places that it's used as well in raft's toolchain, if someone could tell me where they all are I can open PRs upgrading all the specific components. I just want to make sure I get them all in one pass.

**Comment by Fullstop000** [comment]
@nrc Do you provide any suggestion?

**Comment by nrc** [comment]
@hntd187 that would be awesome, I would like to update, but haven't had the time to do it. The upstream crates to change are:

* [grpc-rs](https://github.com/tikv/grpc-rs) multiple crates
* [protobuf-build](https://github.com/tikv/protobuf-build)

The following are downstream, but if you're interested in sending PRs to these projects too, we'd really appreciate it!

* [kvproto](https://github.com/pingcap/kvproto)
* [tikv](https://github.com/tikv/tikv) multiple crates
* [pprof](https://github.com/tikv/pprof-rs) 
* [tipb](https://github.com/pingcap/tipb)
