### ISSUE TITLE
Quorum change should check read index

### ISSUE THREAD

**Issue by BusyJay** [tikv/raft-rs#345]
When quorum changes due to configuration change or quorum function change, read index should be checked eagerly. Otherwise read index will not be advanced until next heartbeat.

**Comment by zd08135** [comment]
Is it solved now?

**Comment by BusyJay** [comment]
I don't think so.

**Comment by zd08135** [comment]
let me read the code first. If no one pick this before I understand it, I want to do some help.

**Comment by hicqu** [comment]
@zd08135 do you get any progress?

**Comment by hicqu** [comment]
@zd08135 I send a PR to fix it because it's a bug influences all TiKV versions.
