### ISSUE TITLE
Joint consensus vs AddNode and RemoveNode

### ISSUE THREAD

**Issue by haraldng** [tikv/raft-rs#352]
How does the performance differ between using Joint Consensus and AddNode and RemoveNode? For example if we want to reconfigure from [1, 2, 3] -> [1, 4, 5], will each AddNode and RemoveNode be handled as a separate reconfiguration?

**Comment by BusyJay** [comment]
You should propose AddNode 4, wait for it's committed, and then apply. Next propose RemoveNode 3, redo the process, and go on. Basically just do one step at a time.

Using `AddNode` and `RemoveNode` is primary for safety consideration. Joint consensus is not a stable feature for now. It's subject to change in the future.
