### ISSUE TITLE
About ConfChange::merge_from_bytes

### ISSUE THREAD

**Issue by blackredscarf** [tikv/raft-rs#370]
I found that the code in examples in 0.6.x branch:
```rust
let mut cc = ConfChange::default();
cc.merge_from_bytes(&entry.data).unwrap();
```
It need to attach
```rust
use protobuf::Message as PbMessage;
```
Otherwise, it cannot build.

I think it is a bad design.

**Comment by BusyJay** [comment]
Why is it a bad design?

**Comment by blackredscarf** [comment]
@BusyJay It seem that the error is caused by a conflict between eraftpb::Message and protobuf::Message. But the tip of compiler given is  
```
method not found in `raft_proto::protos::eraftpb::ConfChange`
```
The api and protobuf::Message look like unconnected. It is difficult to find out.

**Comment by BusyJay** [comment]
I believe compiler is smart enough to give a suggestion to add "use protobuf::core::Message;". This is more related to rust compiler itself, rather than the project. This usage pattern is very common in the rust world, I don't think it's an issue.
