### ISSUE TITLE
Second ConfChange never gets committed

### ISSUE THREAD

**Issue by haraldng** [tikv/raft-rs#373]
I want to replace one node in my raft cluster that initially has 3 nodes: [1,2,3]. I do it by first adding and then removing a node. Reproduce by:

1. Call `propose_conf_change(AddNode)`  // add node4
2. Commit when receiving in the ready state: `RawRaft.raft.add_node(...)` // remove node1
3. Call `propose_conf_change(RemoveNode)`

The second proposed ConfChange never gets committed. I have tried the other way around as well i.e. first remove and then add node.

**Comment by BusyJay** [comment]
Did you advance raft with latest applied index? raft-rs doesn't allow proposing new conf change until last one is applied.

**Comment by haraldng** [comment]
Thanks for your help @BusyJay, I was indeed trying to propose the new conf change before advancing. If the leader is removed, does the user need to make another node candidate? Right now, after advancing, in the logs the removed node is still the leader but it is not in the configuration.

I logged `raw_raft.raft.prs().configuration()` and `raw_raft.raft.leader_id`: `Configuration { voters: {4, 2, 3}, learners: {} }, leader: 1`

**Comment by BusyJay** [comment]
raft-rs doesn't do the clean up jobs. The application is expected to apply the conf remove and destroy self.

**Comment by haraldng** [comment]
I see, thank you :)
