### ISSUE TITLE
MemStorage first_index is different with etcd's

### ISSUE THREAD

**Issue by Fullstop000** [tikv/raft-rs#374]
I found that the `first_index()` implementation for `MemStorage` is different with etcd's
https://github.com/tikv/raft-rs/blob/aaa67943fb3e6b0b5398517637841afa2d07ca04/src/storage.rs#L175-L180

https://github.com/etcd-io/etcd/blob/b0d2edfc682a4dd15267088b726cee38e54b0e9f/raft/storage.go#L161-L164

Is this a special behavior relate to  https://github.com/tikv/raft-rs/pull/353 or something else?

**Comment by BusyJay** [comment]
It's introduced by #195. #353 makes it behaves more like etcd again, though with different implement.

**Comment by Fullstop000** [comment]
etcd's approach creates a dummy entry with index 1 when initializing a new MemStorage 🤔. It seems the implementation in `raft-rs` is more comprehensive.
