### ISSUE TITLE
The serialization of Entry

### ISSUE THREAD

**Issue by blackredscarf** [tikv/raft-rs#377]
I try to implement my own Storage. I need to serialize/deserialize an eraftpb::Entry to/from bytes. Are there some api like `to_bytes()` or `from_bytes()` providing? Or other advice?

**Comment by BusyJay** [comment]
Yes. Entry is a protobuf struct, you can use protobuf/prost library, depend on your choice, to serialize it to bytes.

**Comment by blackredscarf** [comment]
Okay. I find out a solution. The api `write_to_bytes` is defined in trait protobuf::Message.
```rust
#[cfg(test)]
mod test {
    #[test]
    fn test_storage() {
        use raft::prelude::Entry;
        use protobuf::Message;

        let mut en = Entry::new();
        en.set_index(2);
        let b = en.write_to_bytes().unwrap();

        let mut en2 = Entry::new();
        en2.merge_from_bytes(&b).unwrap();

        assert_eq!(2, en2.get_index());
    }
}
```
