### ISSUE TITLE
The example `five_mem_node` can not work

### ISSUE THREAD

**Issue by Uchiha007** [tikv/raft-rs#408]
**Describe the bug**
The example five_mem_node can not work properly.

**To Reproduce**
1. Just run 'cargo run --example five_mem_node'
2. Output with message `MsgHeartbeat` and `MsgHeartbeatResponse` continuously

**Expected behavior**
Finished 100 proposals and exit.

**System information**
* CPU architecture: macOS
* Distribution and kernel version: 10.14.6 (18G6032)

**Additional context**
The commit in the `MemStorageCore.raft_state.hard_state` alway stays the fixed value and affects snapshot that sends to the followers.

**Comment by gengliqi** [comment]
It is caused by not handling the `commit_index` in `LightReady` from `advance`. 
I will send a PR to fix it.
