### ISSUE TITLE
the serialize of raft-proto.eraftpb.Entry

### ISSUE THREAD

**Issue by BanBuDu0** [tikv/raft-rs#413]
**Is your feature request related to a problem? Please describe.**
I try to use raft-rs to build a KV-server, and we all know that raft's log entries is a persistent state on all servers. And what I want to do is that when an entry is committed, I serialize it and simply append it to the end of the persist-file. **But I failed to serialize the Entry struct.**

**Describe the solution you'd like**
If the Entry can be serialized or some other way I can persist the raft's log entries. 

 NOTE that I got failed in trying to use bincode = "1.3.1" to serialized the Entry

**Comment by BusyJay** [comment]
We use protobuf to do serialization, which should be done by `entry.write_to_bytes()`. Remember to `use protobuf::Message` to use the method.

**Comment by BanBuDu0** [comment]
> We use protobuf to do serialization, which should be done by `entry.write_to_bytes()`. Remember to `use protobuf::Message` to use the method.

Thanks, `entry.write_to_bytes()` it works. But I am confused that why I can use `write_to_bytes` this function, because I can't find this function in eraftpb.rs. And in my mind, `struct.function` means the function should be implemented by the struct.

**Comment by BusyJay** [comment]
> struct.function means the function should be implemented by the struct.

Not necessary. You can learn how it works at https://doc.rust-lang.org/book/ch10-02-traits.html.
