### ISSUE TITLE
Optimize memory footprint of raft state machine

### ISSUE THREAD

**Issue by BusyJay** [tikv/raft-rs#419]
After introducing [memory tracing](https://github.com/tikv/rfcs/pull/59) in TiKV, we found that the memory footprint could be very large if there were too many raft state machine. Most of them came from the inflight vector. Supposing `max_inflight_messages` was set to 4096, and there were 3 peers, leader would need to allocate 3 * 4096 * 8 = 96K memory. If there were 100k regions, then the virt memory became 9.1 GiB. And most of the memory were idle and perhaps never visited again.

There are many possible optimizations for this situation. On the one hand, if we can build a global flow control for all raft state machines, then the memory usage can be reduced; on the other hand, if we can reduce the total number of regions, the impact of flow control can also be omitted. But for the short term, I think it's easy to allocate lazily for inflight vector. We can use a linked list to allocate block by block and free them when it's idle. Because most raft state machines should be idle when it comes to 100k, so there will be only one block for all inflight vector. If each block is allocated as 512, then the memory footprint can be reduced to 572MiB, which is reasonably small enough.

**Comment by accelsao** [comment]
Does the "idle" here mean, we do not get the `msg_append_response` for a while, therefore the memory is not freed?

**Comment by BusyJay** [comment]
What I mean is all replications have finished and there are no further `MsgAppend`.

**Comment by accelsao** [comment]
Is it better to use `VecDeque` for ring buffer instead of `LinkedList`? I think we just need `push`, `pop`  for `Inflights`.

**Comment by BusyJay** [comment]
Popping items won't free memory either. To free memory, `shrink_to_fit` needs to be called.

**Comment by accelsao** [comment]
I see, I can try to replace `Vec` to `LinkedList`

**Comment by BusyJay** [comment]
`LinkedList` is probably not a good idea. How about keeping use a `Vec` and support shrinking?

**Comment by accelsao** [comment]
but when to shrink?
1. every time after free, but it maybe too frequent
2. set a shrink timeout in `Inflight`

**Comment by BusyJay** [comment]
A public API in raft node should be enough. This is usually not a problem for users only use small amount of raft state machine. For systems like TiKV build a lot of state machine, they may put raft node into hibernation. A public API can allow them to free resource before going to sleep.

**Comment by accelsao** [comment]
Do you mean we create an pub API for `shrink`, so make it optional for users?

**Comment by BusyJay** [comment]
No, what I mean is a public API to notify raft node to release resource. It may only free inflight buffer for now.

**Comment by accelsao** [comment]
I see

**Comment by accelsao** [comment]
If we use `Vec`, after `shrink`, we might only reduce the mem that is after `self.start + self.count`, but not the mem before `self.start`,, is this expected?

**Comment by accelsao** [comment]
And maybe I need an API for `reallocate`? Just `reserve` some spaces for buffer.

**Comment by BusyJay** [comment]
>  we might only reduce the mem that is after self.start + self.count, but not the mem before self.start, is this expected?

This can be rare. The function is expected to be called when it's idle, during that time, `self.count` is probably 0, so the whole vec can be reclaimed.
