### ISSUE TITLE
Proposal: Follower Read Optimization

### ISSUE THREAD

**Issue by ywave620** [tikv/raft-rs#427]
# Follower Read Optimization

In this post, I propose an optimization of `Follower Read` mentioned in the Raft phd paper. The basic idea dosen't change, the follower will ask the leader for its commitIndex and use it as the readIndex. However, we let follower instead of leader itself to confirm its leadership.

*Define readIndex: This is the read interface provided by Raft library. The application starts a read request. Then, Raft(leader or not) return an readIndex to the application. Raft makes sure that the application can executes the read against the state machine after applying readIndex entry without violating linearizability*

### Algorithm

- Starts with a follower receives a read request, we call this follower *Fr*
- Let *t* be the currentTerm of *Fr*, *Fr* sends out `ConfirmLeadership` RPC to all other servers
- Receiver will reply OK if its currentTerm <= *t*
- If *Fr* gets N/2 OK response, *Fr* can confirm that at the time it sends the RPC, there is no leader in term > *t* (N is the number of nodes)
- The leader in term *t* will not only reply OK(it will definitely reply OK), but also its commitIndex. Moreover, the leader must commit an entry in term *t* before it replies
- *Fr* can use the returned commitIndex as the readIndex (see the Proof below)

### Proof

The proof is not complicated at all. 

Let's call the timepoint at which *Fr* sends out `ConfirmLeadership` *T*. Given that N/2 nodes reply OK, currentTerm of each of those N/2 nodes at *T* <= *t*, combined with currentTerm of *Fr* at *T* is *t*, we know that there is no leader in term > *t* at *T*.

Let's refer the commitIndex of the leader in term *t* as *LCt*. If the leader in term *t* has successfully committed an entry in term *t*, then *LCt* is the greatest commitIndex across the cluster before the leader in term *t* loses its leadership

Now given that

- The leader in term *t* reply only when it has committed an entry in term *t*
- *Fr* does get a reply from the leader in term *t*

Combined with there is no leader in term > *t* at *T*, we know the returned *LCt* >= the greatest commitIndex across the cluster at *T* :)

### Example

Let's walk through this using a typical setup including two datacenters and 5 nodes. Arrow denotes message sending/receving, ① is sent before ②, ② is sent before ③, so on and so forth.

In most cases
![image-20210413131931589](https://user-images.githubusercontent.com/60539365/114503858-82316200-9c60-11eb-98e0-48899ca643ac.png)

1. *Fr* sends out `ConfirmLeadership` RPC
2. another follower in the same datacenter responses OK and the leader in the different datacenter response OK and its commitIndex

In the case where the leader in term *t* has not yet committed an entry in term *t* when receiving `ConfirmLeadership` RPC. (This looks similar to the original `Follower read` if we take out all ① except the one between leader and *Fr* and take out ②)
![image-20210413131911276](https://user-images.githubusercontent.com/60539365/114504133-f23fe800-9c60-11eb-86a7-0a3998167994.png)

1. *Fr* sends out `ConfirmLeadership`  RPC
2. another follower in datacenter2 responses OK
3. leader in term *t* sends out `AppendEntries` to try to commit an entry in term *t*
4. leader in term *t* gets `AppendEntries` responses from two followers in datacenter1 and updates its commitIndex
5. leader responses OK and its commitIndex to *Fr*

### Error Handling

- If *Fr* can not communicate with the leader in term *t* or the leader can not commit an entry in term *t*, *Fr* will end up with waiting indefinitely. To avoid this problem, *Fr* needs to quit serving the read request either when it gets a message with a term > *t* or after a timeout.
- If *Fr* receives less than N/2 OK responses(due to failover), it quits.

### Evaluation

- We reduce one intra-datacenter RTT of serving a read request in most cases compared with the original `Follower Read`.
- We shed load of the leader significantly hence increase the overall throughput of the system. Before, the leader needs to send and receive 5 messages(`Follower Read` request/response * 1, `AppendEntries` request/response * 4) for every read request. Now it only needs to receive and send one message in most cases.
- If *Fr* gets a `ConfirmLeadership`  from leader, there is a big change that the entry in readIndex has been added to its log. However, it is not rare that the commitIndex of *Fr* has not yet been advanced to the readIndex, in this case, we can update its commitIndex immediately instead of waiting for the next `AppendEntries`.

**Comment by BusyJay** [comment]
Interesting. Why not use lease read instead?

**Comment by ywave620** [comment]
> Interesting. Why not use lease read instead?

we assume no max clock drift bound across the cluster

**Comment by gengliqi** [comment]
Good idea! I think it's useful if users don't depend on leader lease.
By the way, the third one of evaluation has already been implemented in this repo.

Actually, the only assumption of the lease used in TiKV is that the relative time difference between any TiKV is not greater than a certain value. Process pause and network delay don't affect the correctness of linearizability.

**Comment by ywave620** [comment]
It requires significant coding effort to prohibit *Process Pause* and *Network Delay* from breaking the system. I just open this issue https://github.com/tikv/tikv/issues/10011

**Comment by BusyJay** [comment]
The proof assumes follower has the latest configuration, which is not always true. I think lease read is the best solution when considering performance.

Perhaps we can move the lease implementation from TiKV to raft-rs, so that users of raft-rs can be benefit from it, and it should also simplify the TiKV code a lot.

**Comment by gengliqi** [comment]
> The proof assumes follower has the latest configuration, which is not always true.

Right. But I think it can be fixed. E.g. through comparing configuration with leader. If they are the same, it's ok, otherwise, wait for the new configuration and retry latter.

**Comment by ywave620** [comment]
> The proof assumes follower has the latest configuration, which is not always true.

Good point

> I think it can be fixed. E.g. through comparing configuration with leader. If they are the same, it's ok, otherwise, wait for the new configuration and retry later, or fall back to original behavior.

👍Thanks for complement
