### ISSUE TITLE
Should 0.6.0-alpha still be used?

### ISSUE THREAD

**Issue by haraldng** [tikv/raft-rs#429]
Hi,

When i started using this crate, version 0.6.0-alpha was the latest stable release on crates. Now 0.5.0 is marked as the latest stable release. Is 0.6.0-alpha abandoned?

**Comment by BusyJay** [comment]
@gengliqi will help release 0.6.0 in this month.

**Comment by bravomikekilo** [comment]
Hi
Is there any new progress? Is 0.6.0 safe to use now?

**Comment by BusyJay** [comment]
0.6.0 was just released.
