### ISSUE TITLE
Is it safe to clear all entries when apply snapshot?

### ISSUE THREAD

**Issue by whfuyn** [tikv/raft-rs#430]
Hi, I'm implementing my storage, but there are some code I don't understand.

I'm not sure why we can discard all entries when apply snapshot. 

If it's an outdated snapshot, there may have uncommitted entries after the snapshot point.

https://github.com/tikv/raft-rs/blob/a5423b241ed641ca0941c816153a9dfc0fdbfad9/src/storage.rs#L197-L214

As the raft paper said, 

"If instead the follower receives a snapshot that describes a prefix of its log (due to retransmission or by mistake),
then log entries covered by the snapshot are deleted but entries following the snapshot are still valid and must be retained."

And I didn't find logic to prevent this when peer handling `MsgSnapshot`, did I miss something?

**Comment by NingLin-P** [comment]
The abovementioned `apply_snapshot` function is usually used in tests to set up the `MemStorage` before the test logic.

> If instead the follower receives a snapshot that describes a prefix of its log (due to retransmission or by mistake)

In this case, `raft-rs` drop the snapshot and fast forward the commit index to `snapshot.index`

https://github.com/tikv/raft-rs/blob/a5423b241ed641ca0941c816153a9dfc0fdbfad9/src/raft.rs#L2524-L2538

**Comment by whfuyn** [comment]
Thanks! I saw this but didn't get it.  Sorry for the trouble. = =
