### ISSUE TITLE
can't create a package from a library

### ISSUE THREAD

**Issue by abdelmonem17** [tikv/raft-rs#431]
I sir, I am usign raft-rs in lib crate and works well and build successfully but when I try to package my library using ```cargo package```  ,I get a compiler error like 

> error[E0609]: no field `auto_leave` on type `raft::prelude::ConfState`
>   --> src\lib.rs:50:31
>                 auto_leave: config.auto_leave,
>                                 ^^^^^^^^^^ unknown field

  so after investigating I saw that the error in raft also so when try to make ```cargo package``` on raft-rs I also have compilation error and it maybe because of using code genrator proto,
  so could you help me and refer to the problem and how to solve it?
  Thank you in advance.

**Comment by BusyJay** [comment]
I think it's because package will use the version from crates.io instead of github. Related to #429.

It's still holiday for most of our team, we will get back to the issue later.

**Comment by abdelmonem17** [comment]
Thank you @BusyJay and I discovered that this is the issue and I we all waiting to publish the release to crate.io

**Comment by BusyJay** [comment]
0.6.0 was just released.
