### ISSUE TITLE
Will AppendEntries be retried after timeout?

### ISSUE THREAD

**Issue by haraldng** [tikv/raft-rs#432]
If a follower does not reply to an AppendEntries, will it be retried after a timeout?

**Comment by whfuyn** [comment]
Yes, it will retry to send MsgAppend. I see this many times in its log. 

But I think it's more like to re-send MsgAppend when follower reply a msg with lower index than a dedicated timer to do this. 

Notice that leader does broadcast MsgHeartBeat periodically. Once follower reply this heartbeat, leader know it outdated and re-send MsgAppend.

Maybe check those handle_*_response fn will be helpful.
https://github.com/tikv/raft-rs/blob/a5423b241ed641ca0941c816153a9dfc0fdbfad9/src/raft.rs#L1785-L1788

**Comment by BusyJay** [comment]
Yes, @whfuyn is correct.
