### ISSUE TITLE
RUSTSEC-2021-0073 in prost 0.7

### ISSUE THREAD

**Issue by lilyball** [tikv/raft-rs#449]
[RUSTSEC-2021-0073](https://rustsec.org/advisories/RUSTSEC-2021-0073.html) was issued recently against prost 0.7, which is used by the `prost-codec` feature flag. It's fixed in prost 0.8, which has some backwards-incompatible changes but not much.

I believe the version of prost can be updated without any code changes. Unfortunately it is technically a breaking change as public raft types implement `prost::Message`, and any clients who use this impl will therefore be broken by the prost update. This could be mitigated going forward by re-exporting `prost` itself and documenting that backward compatibility of the prost-codec feature requires clients who wish to use the `prost::Message` impls to use the re-exported prost. Or duplicate the types so the ones that implement `prost::Message` are private. But for this particular update, the technically-correct thing to do is update the version to 0.7.

The rationale for going ahead and doing this now is anyone using [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) will by default get an error about this RUSTSEC.

**Comment by BusyJay** [comment]
We don't use `timestamp` types. As all fields of protobuf types are public, so users of 0.7 should be able to get around the issue without breaking changes.

raft-rs can upgrade prost to 0.8 in v0.7.0.

**Comment by Uchiha007** [comment]
I have the same problem.
