### ISSUE TITLE
How does learner become follower?

### ISSUE THREAD

**Issue by sargarass** [tikv/raft-rs#457]
From my tests there is no automatic transmission from learner state to follower in v0.6. How to make it right then? I suppose it could be done before ticking the leader's raft. 

0. Does Raft-rs track the learners status or should I do it by using ConfState after `apply_conf_change`? Etcd's ProgressTracker has field `IsLearner bool`. 

1. Is it enough for the leader to check ProgressTracker of the learners to ensure they match his commited_index `(learner's progress.committed_index == leader's raft.raft_log.committed && learner's ProgressState != Snapshot)`?
Or maybe a learner's `state == ProgressState::Replicate` is sufficient? 

2. Should the leader propose new configuration with exactly one node transmitted from learner to follower at a time or one ConfChangeV2 with all the learner ids and `transition = Implicit` will do the thing? 

3. Is it possible that in the future this transition will be made by raft-rs?

**Comment by BusyJay** [comment]
> 0. Does Raft-rs track the learners status or should I do it by using ConfState after apply_conf_change? 

Raft-rs tracks the status in configuration. It's complicated whether a peer is learner or not when considering joint state. I suggest application also keep tracking the confstate.

> 1. Is it enough for the leader to check ProgressTracker of the learners to ensure they match his commited_index

It depends on what do you want. If you just want to see if it's safe to promote a learner to voter, you can check the implementation in [TiKV](https://github.com/tikv/tikv/blob/6d0edd7e690d376e651aecf6f0bbefdeec22c390/components/raftstore/src/store/peer.rs#L2408-L2520), I think it's the most suitable way without depending on much details of raft-rs.

> 2. Should the leader propose new configuration with exactly one node transmitted from learner to follower at a time or one ConfChangeV2 with all the learner ids and transition = Implicit will do the thing?

Either way is OK. It depends on how much you want to control the process. TiKV choose to use ConfChangeV2 to promote a learner and demote a voter at the same time with transition set to explicit. You may want to check out https://github.com/tikv/rfcs/blob/master/text/0054-joint-consensus.md to see how TiKV adapts joint consensus.

> 3. Is it possible that in the future this transition will be made by raft-rs?

I'm afraid no. Learner is a standalone role that can performs without becoming a voter. So raft-rs will not promote it automatically. For example, TiDB [uses](https://en.pingcap.com/blog/how-tidb-htap-makes-truly-hybrid-workloads-possible) voters and learners at the same time to achieve isolated HTAP with strong consistency.

**Comment by BusyJay** [comment]
It's the minimal index of available logs minus one.
