### ISSUE TITLE
Where is struct Message defined? 

### ISSUE THREAD

**Issue by nianxiaoyi** [tikv/raft-rs#467]
I read the raft-rs source code in idea, but I couldn't found where struct Message defined
![image](https://user-images.githubusercontent.com/79825922/156763088-726d28b0-1eca-4277-b6e6-841e7b66900a.png)

Therefore I couldn't  know what default value for the message.
![image](https://user-images.githubusercontent.com/79825922/156763173-bf52d110-fd92-4158-a269-0e2a7434e79c.png)

**Comment by BusyJay** [comment]
It's a protobuf struct defined at https://github.com/tikv/raft-rs/blob/2357cb22760719bcd107a90d1e64ef505bdb1e15/proto/proto/eraftpb.proto#L71-L92.

**Comment by nianxiaoyi** [comment]
> It's a protobuf struct defined at
> 
> https://github.com/tikv/raft-rs/blob/2357cb22760719bcd107a90d1e64ef505bdb1e15/proto/proto/eraftpb.proto#L71-L92
> 
> .
Thank you very much

**Comment by nianxiaoyi** [comment]
good
