### ISSUE TITLE
Using PROST in `Error`

### ISSUE THREAD

**Issue by e-ivkov** [tikv/raft-rs#470]
Seems like if the crate is built with `prost-codec` feature - then prost error should be there https://github.com/tikv/raft-rs/blob/2357cb22760719bcd107a90d1e64ef505bdb1e15/src/errors.rs#L27

**Comment by pidb** [comment]
You need to change the prost version to be same with this library

**Comment by BusyJay** [comment]
We use protobuf-build to unify the APIs and use rust-protobuf versions, that's why there is only one type of error.

**Comment by tisonkun** [comment]
Closed as answered.

Out of thread, I wonder about the rationale of choosing between rust-protobuf and prost. Is there some best practices or benchmark?

**Comment by BusyJay** [comment]
We prefer rust-protobuf because it's more function-complete and well proved in production. In the long term, I think the [official protobuf](https://github.com/protocolbuffers/protobuf/tree/main/rust) implementation is preferred.
