### ISSUE TITLE
Clarification needed: rejecting confchange

### ISSUE THREAD

**Issue by rosik** [tikv/raft-rs#474]
The docstring for `apply_conf_change` says:
https://github.com/tikv/raft-rs/blob/2357cb22760719bcd107a90d1e64ef505bdb1e15/src/raw_node.rs#L394-L399

Are there any examples when it makes sense to reject a conf change?

What restrictions are imposed on a rejection predicate implementation? Is it implied, that the decision (whether to accept of to reject the conf change) *MUST* be deterministic and consistent across all instances?

**Comment by BusyJay** [comment]
> What restrictions are imposed on a rejection predicate implementation? 

For example, in TiKV, there is an epoch mechanism, all commands have to match the epoch to be processed. If a confchange is bind to a stale epoch, it will be just skipped even it's committed. Application is free to use any conditions it wants.

> Is it implied, that the decision (whether to accept of to reject the conf change) MUST be deterministic and consistent across all instances?

Yes, all nodes must take the same decision when apply the log at the same index.
