### ISSUE TITLE
Unclear documentation for Progress maybe_snapshot_abort

### ISSUE THREAD

**Issue by agourlay** [tikv/raft-rs#477]
The documentation on `maybe_snapshot_abort` is unclear regarding what the function actually does.

```rust
  /// Unsets pendingSnapshot if Match is equal or higher than
  /// the pendingSnapshot
  #[inline]
  pub fn maybe_snapshot_abort(&self) -> bool {
      self.state == ProgressState::Snapshot && self.matched >= self.pending_snapshot
  }
```

1. The function does not unset the `pendingSnapshot` field. Is it an oversight?
2. The naming `maybe_snapshot_abort` is a bit confusing. From my understanding the snapshot is complete and not aborted. WDYT?

Thank you for this nice library :+1:

**Comment by BusyJay** [comment]
The naming is wrong. It should be `is_snapshot_caught_up`.
