### ISSUE TITLE
Adopt the DCO over a CLA.

### ISSUE THREAD

**Issue by Hoverbear** [tikv/raft-rs#5]
In an effort to reduce friction in accepting community contributions, I would propose in experimenting with using the [Developer's Certificate of Origin](https://developercertificate.org/) over a Contributor License Agreement for this particular repository.

The DCO is as follows:

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

```

As you can see this is quite simple and does not include many scary legal terms. We can have this done via a signed-off-by.

We can use the [available integration](https://github.com/probot/dco) to enforce this easily.

## Rationale from Other Companies

* [Chef](https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/)
* [Docker](https://blog.docker.com/2014/01/docker-code-contributions-require-developer-certificate-of-origin/)

## Alternatives

In lieu of this, we could simply not require any. Or keep using a CLA. All options are valid.

**Comment by siddontang** [comment]
@Hoverbear 

We use https://github.com/cla-assistant/cla-assistant now, you can have a try.

**Comment by Hoverbear** [comment]
TiKV has now adopted the DCO! I think we can move forward with this.

**Comment by siddontang** [comment]
@Hoverbear 

No, now raft is still in pingcap, we need to use CLA.

**Comment by Hoverbear** [comment]
:cry: Okay.

**Comment by BusyJay** [comment]
Closed as DCO is used.
