### ISSUE TITLE
Please release 0.7.0 on `crates.io`

### ISSUE THREAD

**Issue by ClSlaid** [tikv/raft-rs#500]
Hello, I'm a developer that's interested in using `TiKV` as a backend of storage.

But current build of `client-rust` keeping on fail and merely changing the dependency of it to git repo will require you to release a 0.7.0 version.

Would you kindly publish a new version?

**Comment by Xuanwo** [comment]
Let's @tikv/maintainers to take a look.

**Comment by BusyJay** [comment]
Now it's released and published.
