### ISSUE TITLE
Picked - Support asynchronous storage writes

### ISSUE THREAD

**Issue by tisonkun** [tikv/raft-rs#519]
File an issue to track the upstream feature "async storage write" - https://github.com/etcd-io/raft/pull/8

Open to comments on whether we should catch it up and if there is a plan.

**Comment by gengliqi** [comment]
raft-rs implemented async storage write in https://github.com/tikv/raft-rs/pull/403 three years ago.

**Comment by tisonkun** [comment]
@gengliqi Thanks for your information!
