### ISSUE TITLE
Feat: add raft config parameters `disable_proposal_forwarding`

### ISSUE THREAD

**Issue by datbeohbbh** [tikv/raft-rs#550]
**Is your feature request related to a problem? Please describe.**
[etcd raft](https://github.com/etcd-io/raft/blob/d8715c5aecc21ab7c539b30f70c3bd7696e5bce0/raft.go#L256C2-L256C27) provides a config param `DisableProposalForwarding` which is useful in case the computation to create proposal must be performed on leader node before added to `raft log` and replicated.

**Describe the solution you'd like**
- Add a configuration option `disable_proposal_forwarding` with default value is `false`.
```rust
pub struct Config {
    ...
    pub disable_proposal_forwarding: bool,
    ...
}
```
- In `step_follower`, forward a proposal if there is a valid leader and `disable_proposal_forward = false`, otherwise return `Error::ProposalDropped`.

**Describe alternatives you've considered**

**Additional context**

**Comment by BusyJay** [comment]
Do you want to implement this feature?

**Comment by datbeohbbh** [comment]
> Do you want to implement this feature?

yes, I can. Please, assign for this feature.

**Comment by BusyJay** [comment]
Thanks!
