### ISSUE TITLE
Probe from index less than match

### ISSUE THREAD

**Issue by wego1236** [tikv/raft-rs#555]
In probe mechanism there is chance for replication starting from an index less than match index in probe state, unlike that in replicate state. For example, a rejected probe response got delayed and is received when the leader falls into another probe state. This is a rare case of cause.

To my understanding, allowing such a smaller index implies we want to tolerate loss of already replicated log entries.
[raft-rs/src/tracker/progress.rs](https://github.com/tikv/raft-rs/blob/63aec467a669dc46da8f6921ed893cf76eda65e4/src/tracker/progress.rs#L193-L197 )
``` rust
        if request_snapshot == INVALID_INDEX {
            self.next_idx = cmp::min(rejected, match_hint + 1);
            if self.next_idx < 1 {
                self.next_idx = 1;
            }

```
In this code, there is chance to make Next < Match. But the invariant in raft is that `Next > Match`.

**Comment by wego1236** [comment]
i also find in etcd it fix this bug in [https://github.com/etcd-io/raft/pull/149](url)

**Comment by BusyJay** [comment]
Good catch! Do you want to port the patch?

**Comment by wego1236** [comment]
Yes，i'll do it right now!
