### ISSUE TITLE
Consider priority during election

### ISSUE THREAD

**Issue by BusyJay** [tikv/raft-rs#68]
There may be differences for several nodes of a cluster, like some nodes are in a far away data center, or some nodes have poor hardware configurations. In such case we would want to make them have less chance to become a leader.

After pingcap/raft-rs#63, we support configuring different randomized timeout range for different nodes, which can make it hard to become leader with a larger timeout. However it can still cause noises. Because as long as the nodes have enough logs, it can still become leader even if other preferred nodes have the same logs.

So I propose to add a priority for every node. A follower votes for a candidate only when one of following prerequisites is met:

1. Candidate has more logs;
2. Candidate has the same logs and its priority is not less than the follower.

This policy is expected to work well when the nodes that are preferred to become leaders can form a quorum. In such case a non-preferred node can become leader only when it has more logs. However a node is not preferred usually means that it takes more time to catch up log for high network latency or poor performance as described above.

**Comment by xiang90** [comment]
@BusyJay Can you propose this to etcd repo as well?

**Comment by BusyJay** [comment]
Sure. I will do it these two days.

**Comment by Notdeath** [comment]
My idea is to set the priority as a parameter and get the priority information from the upper store when generating the raft node. The default setting is intermediate level. Then level up or down. But does the node transfer need to modify the priority of the raft, so does it require updating from the store every time?

**Comment by BusyJay** [comment]
Interesting. I guess allowing updating priority during runtime should be enough?

**Comment by dimstars** [comment]
Do we automatically prioritize through hardware performance (such as CPU frequency, network latency) or StoreLabel (whether the address is local), or do we just set the priority manually?

**Comment by BusyJay** [comment]
Just setting priority manually is enough, let's keep the raft library simple.

**Comment by dimstars** [comment]
How can I test an election after a priority change? Once I put the "Raft" in the "Network" for election, I couldn't borrow the "Raft" as mutable to change its priority.

**Comment by BusyJay** [comment]
You can check out following test case:

https://github.com/tikv/raft-rs/blob/b9891b673573fad77ebcf9bbe0969cf945841926/harness/tests/integration_cases/test_raft.rs#L4814-L4881

**Comment by dimstars** [comment]
Thanks, it worked. And I've found the available function in the HashMap following the error message.
pub fn get_mut<Q: ?Sized>(&mut self, k: &Q) -> Option<&mut V>

**Comment by dimstars** [comment]
Should I combine different log states when doing priority election testing? Such as:
Log: out of date,  priority: high
Log: out of date,  priority: low
Log: up to date,   priority: high
Log: up to date,   priority: low

**Comment by BusyJay** [comment]
Yes. And also cases when priority are the same.

**Comment by pankhudinigam** [comment]
Hi team, are there any timelines of when this will be released? 
Also, for now, is there a workaround I can use to get a similar effect?

**Comment by BusyJay** [comment]
We are currently work on porting joint consensus support from etcd. Next version may not be released until the work is done. It's expected to be done before the end of this month.

You should be able to use the `min-election-timeout` and `max-election-timeout` to change the range of election timeout of some node to get a similar effect.
